esphome:
  name: sensy_two
  includes:
    - components/sensy-two/sensy_two_component.h

uart:
  id: sensy_uart
  baud_rate: 115200
  tx_pin: 17
  rx_pin: 16

custom_component:
  - lambda: |-
      auto sensy = new esphome::sensytwo::SensyTwoComponent(&sensy_uart);
      id(sensy_component) = sensy;
      return sensy->get_person_sensors();
    components: [sensy_component]

