esphome:
  name: sensy-two
  friendly_name: Sensy Two 
  name_add_mac_suffix: True
  project: 
    name: Sensy-Two.S2 mmWave Sensor
    version: v0.0.1
    
  includes:
    - components/sensy_two/sensy_two_component.h

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components

wifi:
  ap:
    ssid: "I am Sensy!"
    ap_timeout: 1min

captive_portal:

esp32_improv:
  authorizer: none
  identify_duration: 10s
  wifi_timeout: 1min

api:

logger:
  level: ERROR
#   level: VERY_VERBOSE
#   logs:
#     wifi: ERROR
#     ms72sf1: VERY_VERBOSE
#     ms72sf1_uart: VERY_VERBOSE
#     esphome: DEBUG
#     default: ERROR
#     sensor: ERROR
#     text_sensor: ERROR
#     template: ERROR
#     uart: ERROR
#     mdns: ERROR
#     esphome.core: ERROR
#     esp32_ble: ERROR
#     esp32_ble_server: ERROR
#     esp32_improv: ERROR
#     captive_portal: ERROR
#     web_server: ERROR
#     api: ERROR
#     api.service: ERROR
#     esp32.preferences: ERROR
#     ota: ERROR
#     number: ERROR
#     ld2450: DEBUG

web_server:
  port: 80
  log: false

ota:
  platform: esphome

uart:
  id: ms72sf1
  baud_rate: 115200
  tx_pin: 17
  rx_pin: 16
  rx_buffer_size: 1024
  # debug:
  #   direction: BOTH
  #   dummy_receiver: false
  #   after:
  #     delimiter: "\n"
  #   sequence:
  #     - lambda: UARTDebug::log_string(direction, bytes);

sensy_two:
  id: sensy_component
  uart_id: ms72sf1
  t1_x:
    id: t1_x
    name: "Target 01 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t1_y:
    id: t1_y
    name: "Target 01 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t1_z:
    id: t1_z
    name: "Target 01 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t1_angle:
    id: t1_angle
    name: "Target 01 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t1_speed:
    id: t1_speed
    name: "Target 01 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t1_distance_resolution:
    id: t1_distance_resolution
    name: "Target 01 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t1_distance:
    id: t1_distance
    name: "Target 01 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t2_x:
    id: t2_x
    name: "Target 02 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t2_y:
    id: t2_y
    name: "Target 02 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t2_z:
    id: t2_z
    name: "Target 02 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t2_angle:
    id: t2_angle
    name: "Target 02 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t2_speed:
    id: t2_speed
    name: "Target 02 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t2_distance_resolution:
    id: t2_distance_resolution
    name: "Target 02 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t2_distance:
    id: t2_distance
    name: "Target 02 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t3_x:
    id: t3_x
    name: "Target 03 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t3_y:
    id: t3_y
    name: "Target 03 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t3_z:
    id: t3_z
    name: "Target 03 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t3_angle:
    id: t3_angle
    name: "Target 03 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t3_speed:
    id: t3_speed
    name: "Target 03 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t3_distance_resolution:
    id: t3_distance_resolution
    name: "Target 03 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t3_distance:
    id: t3_distance
    name: "Target 03 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t4_x:
    id: t4_x
    name: "Target 04 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t4_y:
    id: t4_y
    name: "Target 04 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t4_z:
    id: t4_z
    name: "Target 04 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t4_angle:
    id: t4_angle
    name: "Target 04 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t4_speed:
    id: t4_speed
    name: "Target 04 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t4_distance_resolution:
    id: t4_distance_resolution
    name: "Target 04 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t4_distance:
    id: t4_distance
    name: "Target 04 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t5_x:
    id: t5_x
    name: "Target 05 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t5_y:
    id: t5_y
    name: "Target 05 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t5_z:
    id: t5_z
    name: "Target 05 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t5_angle:
    id: t5_angle
    name: "Target 05 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t5_speed:
    id: t5_speed
    name: "Target 05 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t5_distance_resolution:
    id: t5_distance_resolution
    name: "Target 05 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t5_distance:
    id: t5_distance
    name: "Target 05 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t6_x:
    id: t6_x
    name: "Target 06 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t6_y:
    id: t6_y
    name: "Target 06 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t6_z:
    id: t6_z
    name: "Target 06 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t6_angle:
    id: t6_angle
    name: "Target 06 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t6_speed:
    id: t6_speed
    name: "Target 06 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t6_distance_resolution:
    id: t6_distance_resolution
    name: "Target 06 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t6_distance:
    id: t6_distance
    name: "Target 06 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t7_x:
    id: t7_x
    name: "Target 07 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t7_y:
    id: t7_y
    name: "Target 07 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t7_z:
    id: t7_z
    name: "Target 07 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t7_angle:
    id: t7_angle
    name: "Target 07 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t7_speed:
    id: t7_speed
    name: "Target 07 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t7_distance_resolution:
    id: t7_distance_resolution
    name: "Target 07 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t7_distance:
    id: t7_distance
    name: "Target 07 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t8_x:
    id: t8_x
    name: "Target 08 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t8_y:
    id: t8_y
    name: "Target 08 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t8_z:
    id: t8_z
    name: "Target 08 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t8_angle:
    id: t8_angle
    name: "Target 08 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t8_speed:
    id: t8_speed
    name: "Target 08 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t8_distance_resolution:
    id: t8_distance_resolution
    name: "Target 08 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t8_distance:
    id: t8_distance
    name: "Target 08 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t9_x:
    id: t9_x
    name: "Target 09 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t9_y:
    id: t9_y
    name: "Target 09 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t9_z:
    id: t9_z
    name: "Target 09 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t9_angle:
    id: t9_angle
    name: "Target 09 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t9_speed:
    id: t9_speed
    name: "Target 09 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t9_distance_resolution:
    id: t9_distance_resolution
    name: "Target 09 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t9_distance:
    id: t9_distance
    name: "Target 09 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  t10_x:
    id: t10_x
    name: "Target 10 X Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-x-box-outline
  t10_y:
    id: t10_y
    name: "Target 10 Y Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-y-box-outline
  t10_z:
    id: t10_z
    name: "Target 10 Z Coordinate"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:alpha-z-box-outline
  t10_angle:
    id: t10_angle
    name: "Target 10 Angle"
    unit_of_measurement: "°"
    accuracy_decimals: 2
    icon: mdi:format-text-rotation-angle-up
  t10_speed:
    id: t10_speed
    name: "Target 10 Speed"
    unit_of_measurement: "cm/s"
    icon: mdi:speedometer
  t10_distance_resolution:
    id: t10_distance_resolution
    name: "Target 10 Distance Resolution"
    unit_of_measurement: "cm"
    icon: mdi:diameter-outline
  t10_distance:
    id: t10_distance
    name: "Target 10 Distance"
    unit_of_measurement: "cm"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
  radar_firmware:
    id: radar_firmware
    name: "RADAR | Firmware"
    entity_category: diagnostic
  radar_mac:
    id: radar_mac
    name: "RADAR | MAC"
    entity_category: diagnostic

number:
  - platform: template
    id: zone1_x_begin
    name: "Zone 1 X Begin"
    min_value: -600
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone1_x_end
    name: "Zone 1 X End"
    min_value: -600
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone1_y_begin
    name: "Zone 1 Y Begin"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone1_y_end
    name: "Zone 1 Y End"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true

  - platform: template
    id: zone2_x_begin
    name: "Zone 2 X Begin"
    min_value: -600
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone2_x_end
    name: "Zone 2 X End"
    min_value: -600
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone2_y_begin
    name: "Zone 2 Y Begin"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone2_y_end
    name: "Zone 2 Y End"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true

  - platform: template
    id: zone3_x_begin
    name: "Zone 3 X Begin"
    min_value: -600
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone3_x_end
    name: "Zone 3 X End"
    min_value: -600
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone3_y_begin
    name: "Zone 3 Y Begin"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: zone3_y_end
    name: "Zone 3 Y End"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true

  - platform: template
    id: exclusion_x_begin
    name: "Exclusion X Begin"
    min_value: -600
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: exclusion_x_end
    name: "Exclusion X End"
    min_value: -600
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: exclusion_y_begin
    name: "Exclusion Y Begin"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
  - platform: template
    id: exclusion_y_end
    name: "Exclusion Y End"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true

  - platform: template
    id: detection_threshold
    name: "Detection Range"
    min_value: 0
    max_value: 600
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: 'id(sensy_component)->set_detection_range_threshold(id(detection_threshold).state);'

  - platform: template
    id: publish_interval
    name: "Publish Interval"
    min_value: 100
    max_value: 1000
    step: 100
    unit_of_measurement: "ms"
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: 'id(sensy_component)->set_publish_interval_ms(id(publish_interval).state);'

  - platform: template
    id: rotation_x
    name: "Rotation X"
    min_value: -180
    max_value: 180
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: 'id(sensy_component)->set_rotation_x_deg(id(rotation_x).state);'

  - platform: template
    id: rotation_y
    name: "Rotation Y"
    min_value: -180
    max_value: 180
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: 'id(sensy_component)->set_rotation_y_deg(id(rotation_y).state);'

  - platform: template
    id: rotation_z
    name: "Rotation Z"
    min_value: -180
    max_value: 180
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: 'id(sensy_component)->set_rotation_z_deg(id(rotation_z).state);'

button:
  - platform: template
    name: "RADAR | Restart Module"
    on_press:
      - lambda: 'id(sensy_component)->radar_restart();'
    entity_category: config
  - platform: template
    name: "RADAR | Capture Points"
    on_press:
      - lambda: 'id(sensy_component)->radar_capture();'
    entity_category: config

sensor:
  - platform: template
    name: "Zone 1 Targets"
    update_interval: 50000ms
    lambda: |-
      return id(sensy_component)->count_targets_in_zone(
        id(zone1_x_begin).state, id(zone1_x_end).state,
        id(zone1_y_begin).state, id(zone1_y_end).state,
        id(exclusion_x_begin).state, id(exclusion_x_end).state,
        id(exclusion_y_begin).state, id(exclusion_y_end).state);

  - platform: template
    name: "Zone 1 Presence"
    update_interval: 50000ms
    lambda: |-
      return id(sensy_component)->count_targets_in_zone(
        id(zone1_x_begin).state, id(zone1_x_end).state,
        id(zone1_y_begin).state, id(zone1_y_end).state,
        id(exclusion_x_begin).state, id(exclusion_x_end).state,
        id(exclusion_y_begin).state, id(exclusion_y_end).state) > 0;

  - platform: template
    name: "Zone 2 Targets"
    update_interval: 50000ms
    lambda: |-
      return id(sensy_component)->count_targets_in_zone(
        id(zone2_x_begin).state, id(zone2_x_end).state,
        id(zone2_y_begin).state, id(zone2_y_end).state,
        id(exclusion_x_begin).state, id(exclusion_x_end).state,
        id(exclusion_y_begin).state, id(exclusion_y_end).state);

  - platform: template
    name: "Zone 2 Presence"
    update_interval: 50000ms
    lambda: |-
      return id(sensy_component)->count_targets_in_zone(
        id(zone2_x_begin).state, id(zone2_x_end).state,
        id(zone2_y_begin).state, id(zone2_y_end).state,
        id(exclusion_x_begin).state, id(exclusion_x_end).state,
        id(exclusion_y_begin).state, id(exclusion_y_end).state) > 0;

  - platform: template
    name: "Zone 3 Targets"
    update_interval: 50000ms
    lambda: |-
      return id(sensy_component)->count_targets_in_zone(
        id(zone3_x_begin).state, id(zone3_x_end).state,
        id(zone3_y_begin).state, id(zone3_y_end).state,
        id(exclusion_x_begin).state, id(exclusion_x_end).state,
        id(exclusion_y_begin).state, id(exclusion_y_end).state);

  - platform: template
    name: "Zone 3 Presence"
    update_interval: 50000ms
    lambda: |-
      return id(sensy_component)->count_targets_in_zone(
        id(zone3_x_begin).state, id(zone3_x_end).state,
        id(zone3_y_begin).state, id(zone3_y_end).state,
        id(exclusion_x_begin).state, id(exclusion_x_end).state,
        id(exclusion_y_begin).state, id(exclusion_y_end).state) > 0;



